### ISSUE TITLE
skidded code

### ISSUE THREAD

**Issue by ghost** [6af/ddoxer#2]
stolen code. screesnshots attached.
![DQWRTIW8oS](https://user-images.githubusercontent.com/76016636/124976158-bdcf9400-dfe3-11eb-8cc7-1c3b94bb1bc9.png)
![XiaFOPyD4N](https://user-images.githubusercontent.com/76016636/124976048-9d9fd500-dfe3-11eb-9d70-84e6a51c330b.png)

**Comment by ghost** [comment]
![sublime_text_IoUeEQy5Bh](https://user-images.githubusercontent.com/76016636/124976285-e9527e80-dfe3-11eb-979e-8cb70fa9e1f3.png)

**Comment by 6af** [comment]
mines better it  has ascii art

**Comment by 6af** [comment]
mine best

**Comment by ghost** [comment]
no
